# Generated by Django 3.1.7 on 2021-03-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='lastReviewed',
            new_name='last_reviewed',
        ),
    ]
