# Generated by Django 3.1.7 on 2021-03-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='lastReviwedAt',
            new_name='last_reviwed_at',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='nextReviewAt',
            new_name='next_review_at',
        ),
    ]
