# Generated by Django 3.1.7 on 2021-03-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20210305_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_reviwed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
